@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri May 15 14:55:28 +0200 2020
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim ss_driver_tb_behav -key {Behavioral:ss_driver:Functional:ss_driver_tb} -tclbatch ss_driver_tb.tcl -view C:/Users/Oyama Plati/Downloads/EEE2020/EEE4120F/FPGA/projects/FPGA_WallClock/ss_driver_tb_behav.wcfg -log simulate.log"
call xsim  ss_driver_tb_behav -key {Behavioral:ss_driver:Functional:ss_driver_tb} -tclbatch ss_driver_tb.tcl -view C:/Users/Oyama Plati/Downloads/EEE2020/EEE4120F/FPGA/projects/FPGA_WallClock/ss_driver_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
