@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat May 16 17:45:32 +0200 2020
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim sram_basic_testbench_behav -key {Behavioral:sram:Functional:sram_basic_testbench} -tclbatch sram_basic_testbench.tcl -view C:/Users/Oyama Plati/Downloads/EEE2020/EEE4120F/FPGA/projects/fullsine/fullsine.srcs/sram/imports/Prac5/sram_basic_testbench_behav.wcfg -log simulate.log"
call xsim  sram_basic_testbench_behav -key {Behavioral:sram:Functional:sram_basic_testbench} -tclbatch sram_basic_testbench.tcl -view C:/Users/Oyama Plati/Downloads/EEE2020/EEE4120F/FPGA/projects/fullsine/fullsine.srcs/sram/imports/Prac5/sram_basic_testbench_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
